version: "3.8"
services:
    qatest:
        image: 'bitnami/symfony:1'
        ports:
            - '8000:8000'
        volumes:
            - '.:/app'
        environment:
            - SYMFONY_PROJECT_NAME=qatest
            - MARIADB_HOST=mariadb
            - MARIADB_PORT_NUMBER=3306
            - MARIADB_USER=admin
            - MARIADB_PASSWORD=admin
            - MARIADB_DATABASE=qatest
        depends_on:
        - mariadb
    mariadb:
        image: 'bitnami/mariadb:10.3'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=admin
            - MARIADB_PASSWORD=admin
            - MARIADB_DATABASE=qatest